//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Пример3Entities1 : DbContext
    {
        public Пример3Entities1()
            : base("name=Пример3Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Вид_оборудования> Вид_оборудования { get; set; }
        public virtual DbSet<Заказы> Заказы { get; set; }
        public virtual DbSet<Заявка> Заявка { get; set; }
        public virtual DbSet<Исполнители> Исполнители { get; set; }
        public virtual DbSet<Материалы> Материалы { get; set; }
        public virtual DbSet<Оборудование> Оборудование { get; set; }
        public virtual DbSet<Отчет> Отчет { get; set; }
        public virtual DbSet<Позиции_заказа> Позиции_заказа { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
        public virtual DbSet<Приоритет_заявки> Приоритет_заявки { get; set; }
        public virtual DbSet<Работники> Работники { get; set; }
        public virtual DbSet<Роли> Роли { get; set; }
        public virtual DbSet<Статус_заявки> Статус_заявки { get; set; }
    }
}
