//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказы()
        {
            this.Позиции_заказа = new HashSet<Позиции_заказа>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_заявки { get; set; }
        public int Количество_деталей { get; set; }
        public string Статус_заказа { get; set; }
        public System.DateTime Дата_заказа { get; set; }
    
        public virtual Заявка Заявка { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Позиции_заказа> Позиции_заказа { get; set; }
    }
}
