//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заявка
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заявка()
        {
            this.Заказы = new HashSet<Заказы>();
            this.Отчет = new HashSet<Отчет>();
        }
    
        public int ID { get; set; }
        public System.DateTime Дата_начала { get; set; }
        public Nullable<System.DateTime> Дата_окончания { get; set; }
        public int ID_оборудования { get; set; }
        public string Описание_проблемы { get; set; }
        public int ID_клиента { get; set; }
        public Nullable<int> ID_исполнителя { get; set; }
        public Nullable<int> ID_статус_заявки { get; set; }
        public Nullable<int> ID_приоритет { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заказы> Заказы { get; set; }
        public virtual Исполнители Исполнители { get; set; }
        public virtual Оборудование Оборудование { get; set; }
        public virtual Приоритет_заявки Приоритет_заявки { get; set; }
        public virtual Работники Работники { get; set; }
        public virtual Статус_заявки Статус_заявки { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Отчет> Отчет { get; set; }
    }
}
