//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Отчет
    {
        public int ID { get; set; }
        public int ID_заявки { get; set; }
        public int ID_клиента { get; set; }
        public Nullable<int> ID_исполнителя { get; set; }
        public System.DateTime Дата_начала { get; set; }
        public Nullable<System.DateTime> Дата_окончания { get; set; }
        public string Результат_работы { get; set; }
    
        public virtual Заявка Заявка { get; set; }
    }
}
