//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Позиции_заказа
    {
        public int ID { get; set; }
        public Nullable<int> ID_заказа { get; set; }
        public Nullable<int> Количество { get; set; }
        public Nullable<int> ID_материала { get; set; }
    
        public virtual Заказы Заказы { get; set; }
        public virtual Материалы Материалы { get; set; }
    }
}
